### ISSUE TITLE
Install/Deploy with influxdb/grafana

### ISSUE THREAD

**Issue by Asher-Shoshan** [kubernetes/heapster#1904] opened 2017-12-06 08:31 UTC
Can't figure out what exactly to do and start using  Heapster in my on-premises Kubernetes cluster.
Downloaded the yaml files and run 'kubectl create -f ..."?
There is 'k8s' db inside the influxdb container.  Should I do something?

**Comment by kawych** [comment] 2017-12-18 14:36
Closing as duplicate of #1903.

**Closed by kawych** 2017-12-18 14:36 UTC
