### ISSUE TITLE
Wrong values of disk/limit metric in metric-export endpoint

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1069] opened 2016-03-15 19:31 UTC
According to @a-robinson observation they are far bigger than expected: hundreds of gigabytes on nodes that only have 10G boot disks.

cc @vishh

**Comment by vishh** [comment] 2016-03-15 19:33
The data surfaced from the kubelet is valid. [Here](https://gist.github.com/pwittrock/bc40a8d3199f26a0df08) is a sample output. I suspect an issue with heapster aggregation.

**Comment by a-robinson** [comment] 2016-03-15 19:39
Sorry, the nodes actually have 100GB boot disks, which is at least on the same scale as the metrics we're seeing, but the metrics are still too high.

**Comment by mwielgus** [comment] 2016-03-15 20:57
Heapster doesn't do any node disk aggregations. Disk metrics in containers are not touched at all so the problem is either in kubelet response parsing or with GKE internal code.

**Comment by vishh** [comment] 2016-03-15 23:05
I could not find any issues in the code either. Closing this issue.

**Closed by vishh** 2016-03-15 23:05 UTC
Labels: Priority/P1
