### ISSUE TITLE
Missing Heapster/InfluxDB/Grafana images

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/heapster#1469] opened 2017-01-17 03:23 UTC
The `README.md` in `/master` suggests that we should use the following guide to install with InfluxDB: [https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md).

That guide instructs us to execute `kubectl create -f deploy/kube-config/influxdb/` from the root of the repo. When doing so, the deployments created by the following to files fail as the related containers are not available, possibly to everyone.

Failure 1: `{repo-root}/deploy/kube-config/influxdb/grafana-deployment.yaml`
line 16: `image: gcr.io/google_containers/heapster-grafana:v4.0.2`
Error Message: Failed to pull image "gcr.io/google_containers/heapster-grafana:v4.0.2": image pull failed for gcr.io/google_containers/heapster-grafana:v4.0.2, this may be because there are no credentials on this request. details: (Tag v4.0.2 not found in repository gcr.io/google_containers/heapster-grafana)

Failure 2: `{repo-root}/deploy/kube-config/influxdb/influxdb-deployment.yaml`
line 16: `image: gcr.io/google_containers/heapster-influxdb:v1.1.1`
Error Message: Failed to pull image "gcr.io/google_containers/heapster-influxdb:v1.1.1": image pull failed for gcr.io/google_containers/heapster-influxdb:v1.1.1, this may be because there are no credentials on this request. details: (Tag v1.1.1 not found in repository gcr.io/google_containers/heapster-influxdb)

I can see one version of each of these containers in gcr, however they are both quite old versions. Is there a way to get access to the latest versions, or have these moved, or are the versions just listed wrong?

**Comment by jcooke89** [comment] 2017-01-17 10:44
I'm experiencing the exact same issue

**Comment by luxas** [comment] 2017-01-20 08:16
@Crassirostris Please push these images (grafana:v4.0.2 and influxdb:v1.1.1)

**Comment by Crassirostris** [comment] 2017-01-20 10:30
@luxas @piosz will handle it

**Comment by judexzhu** [comment] 2017-01-21 00:26
Excuse me , first all , thanks for all the contribute and your hard work , really great job,  and I'm stilling facing this issue, should I use the older version image and should I wait for awhile and it will be fixed really soon ? thanks

**Comment by idcrook** [comment] 2017-01-21 01:01
I was about to file an issue, but I discovered this one.  Noticed that the latest images are there on `gcr.io`, but have just moved into per-ARCH id's now. Hope that helps.  I'll submit a PR if that helps things along.

```diff
modified   deploy/kube-config/influxdb/grafana-deployment.yaml
@@ -13,7 +13,7 @@ spec:
     spec:
       containers:
       - name: grafana
-        image: gcr.io/google_containers/heapster-grafana:v4.0.2
+        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
         ports:
           - containerPort: 3000
             protocol: TCP
modified   deploy/kube-config/influxdb/influxdb-deployment.yaml
@@ -13,7 +13,7 @@ spec:
     spec:
       containers:
       - name: influxdb
-        image: gcr.io/google_containers/heapster-influxdb:v1.1.1
+        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
         volumeMounts:
         - mountPath: /data
           name: influxdb-storage
```

**Comment by Crassirostris** [comment] 2017-01-21 12:00
@idcrook There's magic inside grafana and heapster makefiles, that will make them work without your change.

IIUC the problem is that this magic is incompatible with gcr, we're working on resolving this issue

@luxas Please correct me, if I'm wrong

**Comment by piosz** [comment] 2017-01-23 08:32
Apologies guys for the confusion. There an issue with gcr.io (#1478).  The images were pushed for specific architecture but there is not generic one. Please use the approach from @idcrook's https://github.com/kubernetes/heapster/issues/1469#issuecomment-274218852.

**Comment by piosz** [comment] 2017-01-23 10:08
Closing in favor of #1478

**Closed by piosz** 2017-01-23 10:08 UTC

**Comment by sjezewski** [comment] 2018-02-06 19:28
FYI this happened to me today. I could not pull either `gcr.io/google_containers/heapster-grafana-amd64:v4.0.2` or `gcr.io/google_containers/heapster-grafana:v4.0.2` on my local machine.

Instead, I used the `grafana/grafana:4.0.2` image on dockerhub. Obvious in retrospect, but I'll have to update some of my scripts which clearly use an old deployment manifest.
