### ISSUE TITLE
Frequency of updating model is too high (145 seconds)

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/heapster#642] opened 2015-10-09 14:58 UTC
Currently, heapster has frequency of model updateds dependent on model resolution. It is 145 seconds for model resolution of 1 minute it is. As a result, horizontal pod autoscaling gets metrics from heapster with 145 seconds lag. This increases latency of horizontal pod autoscaler too much.

Proposed fix:
1. Make model update frequency configurable #635.
2. Reduce it to 65 seconds for 1 minute model resolution.

This will reduce latency of horizontal pod autoscaler lag to 65 seconds which should be acceptable for 1.1.

**Comment by jszczepkowski** [comment] 2015-10-09 14:59
@vishh
Why the current frequency is so high? Can we do p.2 (reduce it to 65 seconds)?

**Comment by jszczepkowski** [comment] 2015-10-09 14:59
CC @piosz @fgrzadkowski @mwielgus

**Comment by vishh** [comment] 2015-10-09 17:10
SGTM. cc @afein

**Comment by vishh** [comment] 2015-10-09 17:13
[Here](https://github.com/kubernetes/heapster/pull/508#discussion_r38687414) is some relevant conversation on this with @afein.

**Comment by afein** [comment] 2015-10-09 18:54
I would strongly recommend resolving #528 alongside #635. The reason is that if the update period is a multiple of the model resolution then some derived model metrics (pods, namespaces, cluster) could incorrectly disregard values during aggregation. 

This behavior is caused by the fact that the same model timestamp is used for both aggregation and updates and it was a tradeoff that was required to avoid adding complex logic that would cause derived metrics to intentionally lag behind in time.

**Comment by jszczepkowski** [comment] 2015-10-09 19:33
The problem here is that we **need** 65 seconds model frequency for 1.1, while #528 will rather not be solved for 1.1. Model frequency of nearly 2.5 minutes is not acceptable from the horizontal pod autoscaler point of view.

**Comment by afein** [comment] 2015-10-09 19:52
Fair enough, but do keep in mind that reducing the model frequency before #528 is resolved might potentially reduce the accuracy of aggregated metrics in a periodic fashion.

 Specifically, I suspect that every 1 in LCM(model_frequency, model_resolution) samples will be incorrectly aggregated to 0.

**Comment by jszczepkowski** [comment] 2015-10-10 17:14
CC @derekwaynecarr

**Comment by awarude** [comment] 2016-09-27 13:53
when can we expect this fix? is there anyway around this problem so that the hpa doesnt wait for 2.5 mins?

**Comment by mwielgus** [comment] 2016-09-28 11:52
Obsolete.

**Closed by mwielgus** 2016-09-28 11:52 UTC

**Comment by DirectXMan12** [comment] 2016-09-30 19:48
(to be more specific, this was fixed in the Heapster refactor that happened a while ago.  The default update interval is currently 1 minute, but, if you're willing to deal with an increased memory footprint, can go as low as 10-15 seconds (you'll want to go higher than 10s, though, otherwise you'll have timing issues with cAdvisor's housekeeping interval in Kubernetes))

**Comment by awarude** [comment] 2016-09-30 19:51
can you point to to the right thread or documentation which shows how that can be configured.

**Comment by DirectXMan12** [comment] 2016-09-30 22:44
`--metric_resolution` argument on the Heapster executable will do it (see `heapster --help`).  You can use it like `--metric_resolution 10s`.
