### ISSUE TITLE
some redundant data in the heapster sink's source data

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/heapster#677] opened 2015-10-27 13:10 UTC
heapster store timeseries of PODs(including their containers ) and events to the external sink.
https://github.com/kubernetes/heapster/blob/master/sinks/external.go#L139
```go
for idx := range esm.externalSinks {
		sink := esm.externalSinks[idx]
		go func(sink sink_api.ExternalSink) {
			glog.V(2).Infof("Storing Timeseries to %q", sink.Name())
			errorsChan <- sink.StoreTimeseries(timeseries)
		}(sink)
		go func(sink sink_api.ExternalSink) {
			glog.V(2).Infof("Storing Events to %q", sink.Name())
			errorsChan <- sink.StoreEvents(kEvents)
		}(sink)
	}
```
**here, just saving the pods' and containers' metric information**, but the `timeseries` contains **some redundant data about some process and cgroup**, i debug this issue,and got these:
*cgroup
```json
{
    "Point": {
        "Name": "uptime", 
        "Labels": {
            "container_base_image": "", 
            "container_name": "/user/0.user/38.session", 
            "host_id": "192.168.11.77", 
            "hostname": "192.168.11.77", 
            "labels": ""
        }, 
        "Start": "2015-10-26T17:14:56Z", 
        "End": "2015-10-26T20:04:10Z", 
        "Value": 10172528
    }, 
    "MetricDescriptor": {
        "Name": "uptime", 
        "Description": "Number of milliseconds since the container was started", 
        "Labels": null, 
        "Type": 0, 
        "ValueType": 0, 
        "Units": 2
    }
}
```
*other process
```json
{
    "Point": {
        "Name": "cpu/usage", 
        "Labels": {
            "container_base_image": "", 
            "container_name": "kubelet", 
            "host_id": "192.168.11.77", 
            "hostname": "192.168.11.77", 
            "labels": ""
        }, 
        "Start": "2015-10-13T19:05:12Z", 
        "End": "2015-10-26T20:04:10Z", 
        "Value": 9654496406507
    }, 
    "MetricDescriptor": {
        "Name": "cpu/usage", 
        "Description": "Cumulative CPU usage on all cores", 
        "Labels": null, 
        "Type": 0, 
        "ValueType": 0, 
        "Units": 3
    }
}
```
The redundant data has common feature is that their `container_base_image` is empty.
Shall we filter these redundant data?

**Comment by vishh** [comment] 2015-10-27 18:15
The base image will be missing for containers that were not started via
kubernetes APIs. In kubernetes, the kubelet (node agent), creates cgroups
to track resource usage of certain node daemons (docker, sshd, etc). This
information is useful to monitor the nodes. Filtering out non-interesting
containers is possible, but it will be difficult to implement in practice
unless we can somehow discover only the interesting ones.
If this is not an issue as of now, I'd recommend not attempting to fix this.

**Comment by huangyuqi** [comment] 2015-10-28 02:02
@vishh ,  thanks for your explanation.

**Comment by piosz** [comment] 2016-09-03 05:42
Closing as this working as intended.

**Closed by piosz** 2016-09-03 05:42 UTC
