### ISSUE TITLE
Intermittent failure to collect metrics from pods

### ISSUE THREAD

**Issue by lattwood** [kubernetes/heapster#1237] opened 2016-08-02 20:49 UTC
Details from log. If I destroy `gum-company2015-3634674971-6y5pt`, a new one will be created and one of the remaining pods will begin to have these intermittent failures.

```
I0802 20:42:05.000211       1 manager.go:79] Scraping metrics start: 2016-08-02 20:41:30 +0000 UTC, end: 2016-08-02 20:42:00 +0000 UTC
I0802 20:42:05.381598       1 manager.go:152] ScrapeMetrics: time: 381.316743ms size: 261
I0802 20:42:35.000242       1 manager.go:79] Scraping metrics start: 2016-08-02 20:42:00 +0000 UTC, end: 2016-08-02 20:42:30 +0000 UTC
I0802 20:42:35.381447       1 manager.go:152] ScrapeMetrics: time: 381.130323ms size: 261
I0802 20:43:05.000302       1 manager.go:79] Scraping metrics start: 2016-08-02 20:42:30 +0000 UTC, end: 2016-08-02 20:43:00 +0000 UTC
I0802 20:43:05.483585       1 manager.go:152] ScrapeMetrics: time: 483.190549ms size: 261
I0802 20:43:35.000221       1 manager.go:79] Scraping metrics start: 2016-08-02 20:43:00 +0000 UTC, end: 2016-08-02 20:43:30 +0000 UTC
I0802 20:43:35.381705       1 manager.go:152] ScrapeMetrics: time: 381.411597ms size: 261
I0802 20:44:05.000240       1 manager.go:79] Scraping metrics start: 2016-08-02 20:43:30 +0000 UTC, end: 2016-08-02 20:44:00 +0000 UTC
I0802 20:44:05.381853       1 manager.go:152] ScrapeMetrics: time: 381.53917ms size: 261
I0802 20:44:35.000195       1 manager.go:79] Scraping metrics start: 2016-08-02 20:44:00 +0000 UTC, end: 2016-08-02 20:44:30 +0000 UTC
I0802 20:44:35.382496       1 manager.go:152] ScrapeMetrics: time: 382.227743ms size: 261
W0802 20:44:42.372981       1 reflector.go:342] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: watch of *api.Namespace ended with: too old resource version: 703066 (709276)
I0802 20:44:56.570481       1 handlers.go:178] No metrics for pod default/gum-company2015-3634674971-6y5pt
I0802 20:44:57.804688       1 handlers.go:178] No metrics for pod default/gum-company2015-3634674971-6y5pt
I0802 20:45:05.000214       1 manager.go:79] Scraping metrics start: 2016-08-02 20:44:30 +0000 UTC, end: 2016-08-02 20:45:00 +0000 UTC
I0802 20:45:05.285976       1 manager.go:152] ScrapeMetrics: time: 285.690109ms size: 261
I0802 20:45:26.572613       1 handlers.go:178] No metrics for pod default/gum-company2015-3634674971-6y5pt
I0802 20:45:27.806737       1 handlers.go:178] No metrics for pod default/gum-company2015-3634674971-6y5pt
I0802 20:45:35.000271       1 manager.go:79] Scraping metrics start: 2016-08-02 20:45:00 +0000 UTC, end: 2016-08-02 20:45:30 +0000 UTC
I0802 20:45:35.485714       1 manager.go:152] ScrapeMetrics: time: 485.374317ms size: 261
I0802 20:46:05.000234       1 manager.go:79] Scraping metrics start: 2016-08-02 20:45:30 +0000 UTC, end: 2016-08-02 20:46:00 +0000 UTC
I0802 20:46:05.381448       1 manager.go:152] ScrapeMetrics: time: 381.136502ms size: 261
```

**Comment by lattwood** [comment] 2016-08-02 21:28
I've increased logging verbosity, and it appears to skip the metrics due to a small difference in container create times. I have no idea where to begin with this. :-/

```
I0802 21:27:05.485307       1 rate_calculator.go:51] Skipping rates for namespace:default/pod:juicyfruit2015-3634674971-6y5pt/container:gum-company2015 - different create time new:2016-08-02 20:37:50.926259126 +0000 UTC  old:2016-08-02 20:37:50.921258978 +0000 UTC
```

**Comment by piosz** [comment] 2016-08-10 06:16
Thanks for reporting. I'll take a look. Which version of Heapster/Kubernetes do you use?

**Comment by lattwood** [comment] 2016-08-10 15:03
Thanks

Kubernetes is 1.3.0, planning to upgrade to 1.3.4 soon.
Heapster is v1.1.0.

I'm in the kubernetes slack if you need me to poke and prod

**Comment by ichekrygin** [comment] 2016-08-15 17:25
Hi guys, it appears this issue prevents us from using HPA.

**Comment by DirectXMan12** [comment] 2016-08-15 21:16
WRT to the rate calculation issue: I'm seeing a weird issue on my setup where, after inserting some debug statements, it appears that occasionally, Heapster receives multiple instances of the same container with slightly different start times (subsecond differences).  This seems to happen much more rarely on the summary API (which appears to round to the second for the timestamps), but still happens occasionally. 

However, I'm not entirely certain that this is also the cause of your missing metrics.  I'll continue to dig.

**Comment by DirectXMan12** [comment] 2016-08-16 02:38
WRT to the rate calculation issue: traced back to kubelet, which seems to be somewhere receiving duplicate container entries from cAdvisor, and is happily just appending to its list, assuming that never happens.  The duplicates seem to have slightly different start times -- off by less than a second.  I'll continue digging tomorrow.

**Comment by DirectXMan12** [comment] 2016-08-16 20:14
Depending  on versions of things involved, this may be a bug in the interaction between systemd and docker, causing a container to show up in at two different keys.  After I updated my system, and then dealt with this: https://github.com/projectatomic/docker/pull/181, the rate calculation problem went away.

**Comment by DirectXMan12** [comment] 2016-08-16 20:15
(if you docker exec into one of your pods and check `/proc/self/cgroup`, what what do you see there?)

**Comment by DirectXMan12** [comment] 2016-08-17 01:19
That could also be causing your missing metrics issue, as "missing metrics" can mean missing "cpu/usage_rate", which is put in place by the rate calculator.

**Comment by danielfm** [comment] 2016-08-17 03:37
@DirectXMan12 I believe I'm running into a similar issue.

Here's my `/proc/self/cgroup` from one of my pods:

```
11:pids:/init.scope/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
10:devices:/init.scope/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
9:perf_event:/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
8:hugetlb:/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
7:cpu,cpuacct:/init.scope/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
6:memory:/init.scope/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
5:cpuset:/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
4:net_cls,net_prio:/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
3:freezer:/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
2:blkio:/init.scope/system.slice/docker-beb8ae2859414c015b34d3e0670c9f59e7827abf50e3355accfda770381aac54.scope
1:name=systemd:/system.slice/docker.service
```

I'm running Kubernetes 1.3.4 / Heapster 1.1.0 / Docker 1.10.3 / CoreOS 1068.8.0 (stable)

**Comment by DirectXMan12** [comment] 2016-08-17 14:20
yeah, based on having both the `/init.scope` prefix and and the plain `/system.slice` prefix, I'd guess that containers are getting doubly reported by Kubelet (with slightly different start times), and thus confusing Heapster.

**Comment by janwillies** [comment] 2016-08-29 18:05
@DirectXMan12 how did you workaround this? I tried with coreos beta channel which has the systemd-cgroup driver, and also with coreos alpha channel, which has the docker-cgroup driver. No luck though

**Comment by lattwood** [comment] 2016-08-29 18:23
@janwillies I had success with using the cgroupfs driver on the docker daemon

**Comment by DirectXMan12** [comment] 2016-08-29 19:49
@janwillies @lattwood it's also fixed in a newer Docker version, there's this patch (https://github.com/projectatomic/docker/pull/181) if you're running on Fedora, and you could also patch your copy of Kubelet to merge those results.

**Comment by DirectXMan12** [comment] 2016-09-06 14:38
closing this in favor of the ongoing discussion about a 1.3/1.4 solution in kubernetes/kubernetes#30939

**Closed by DirectXMan12** 2016-09-06 14:38 UTC
Labels: bug, Priority/P2

**Comment by gaddamidianil** [comment] 2016-11-04 18:51
@DirectXMan12 
I assume your analysis is right.
when multiple pods running, its not capturing the metrics. When I tried with single pod, heapster doesnt show 'no metrics error' and hpa works fine. 
Looking forward for solution on multiple pods.
