### ISSUE TITLE
my  monitoring-grafana  status CrashLoopBackOff

### ISSUE THREAD

**Issue by juixtu** [kubernetes/heapster#1712] opened 2017-07-05 17:04 UTC
I follow the steps to install heapster 
Finally appeared：
```
kube-system   etcd-master                             1/1       Running            0          1d
kube-system   heapster-84017538-t8f69                 1/1       Running            0          3h
kube-system   kube-apiserver-master                   1/1       Running            0          1d
kube-system   kube-controller-manager-master          1/1       Running            0          1d
kube-system   kube-dns-2425271678-0kh71               3/3       Running            0          1d
kube-system   kube-proxy-8xkgh                        1/1       Running            0          1d
kube-system   kube-proxy-qxc22                        1/1       Running            0          1d
kube-system   kube-proxy-zvmmj                        1/1       Running            0          1d
kube-system   kube-scheduler-master                   1/1       Running            0          1d
kube-system   kubernetes-dashboard-2209332821-w4zb0   1/1       Running            0          1d
kube-system   monitoring-grafana-762361155-88f60      0/1       CrashLoopBackOff   46         3h
kube-system   monitoring-influxdb-2097753575-d9v81    1/1       Running            0          3h
kube-system   weave-net-6pklf                         2/2       Running            0          1d
kube-system   weave-net-d3pr0                         2/2       Running            1          1d
kube-system   weave-net-hlt7n                         2/2       Running            0          1d
```
View the pod log：

```
[root@master httpd]# kubectl logs monitoring-grafana-762361155-88f60 -n kube-system
Starting a utility program that will configure Grafana
Starting Grafana in foreground mode
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp [::1]:3000: getsockopt: connection refused. Retrying after 5 seconds...
t=2017-07-05T16:37:34+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory%!(EXTRA []interface {}=[])"
```
View the pod describe:

```
[root@master httpd]# kubectl describe pod monitoring-grafana-762361155-88f60 -n kube-system
Name:		monitoring-grafana-762361155-88f60
Namespace:	kube-system
Node:		node2/192.168.80.129
Start Time:	Wed, 05 Jul 2017 21:01:24 +0800
Labels:		k8s-app=grafana
		pod-template-hash=762361155
		task=monitoring
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"monitoring-grafana-762361155","uid":"0b875064-6182-11e7-9205...
Status:		Running
IP:		10.47.0.2
Created By:	ReplicaSet/monitoring-grafana-762361155
Controlled By:	ReplicaSet/monitoring-grafana-762361155
Containers:
  grafana:
    Container ID:	docker://170fc1f19515846c2086989f48ee034dd3a4bb924cd65812972d3e2a95f2b805
    Image:		gcr.io/google_containers/heapster-grafana-amd64:v4.2.0
    Image ID:		docker-pullable://gcr.io/google_containers/heapster-grafana-amd64@sha256:9bf6d8edf8884f19209ca424308e28aa0cbaaeb9f02b4ac237effb6011a09c1f
    Port:		3000/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Thu, 06 Jul 2017 00:37:34 +0800
      Finished:		Thu, 06 Jul 2017 00:37:34 +0800
    Ready:		False
    Restart Count:	47
    Environment:
      INFLUXDB_HOST:			monitoring-influxdb
      GF_SERVER_HTTP_PORT:		3000
      GF_AUTH_BASIC_ENABLED:		false
      GF_AUTH_ANONYMOUS_ENABLED:	true
      GF_AUTH_ANONYMOUS_ORG_ROLE:	Admin
      GF_SERVER_ROOT_URL:		/
    Mounts:
      /var from grafana-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wn034 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  grafana-storage:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  default-token-wn034:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-wn034
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From		SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----		-------------			--------	------		-------
  3h		4m		48	kubelet, node2	spec.containers{grafana}	Normal		Pulled		Container image "gcr.io/google_containers/heapster-grafana-amd64:v4.2.0" already present on machine
  3h		4m		48	kubelet, node2	spec.containers{grafana}	Normal		Created		Created container
  3h		4m		48	kubelet, node2	spec.containers{grafana}	Normal		Started		Started container
  3h		6s		1023	kubelet, node2	spec.containers{grafana}	Warning		BackOff		Back-off restarting failed container
  3h		6s		1023	kubelet, node2					Warning		FailedSync	Error syncing pod
```

I want to know how to solve
thanks！

**Comment by DirectXMan12** [comment] 2017-07-05 17:41
This is a known issue with the current Grafana image, it looks like: duplicate of https://github.com/kubernetes/heapster/issues/1709

**Closed by DirectXMan12** 2017-07-05 17:41 UTC
Labels: sink/influxdb, support

**Comment by juixtu** [comment] 2017-07-06 16:23
@DirectXMan12 thanks!
