### ISSUE TITLE
influxdb-amd64:v1.3.3 not found

### ISSUE THREAD

**Issue by jicki** [kubernetes/heapster#1798] opened 2017-09-04 03:53 UTC
```
docker pull gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3
Error response from daemon: manifest for gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3 not found
```

**Comment by jicki** [comment] 2017-09-04 03:55
@luxas

**Comment by voyalab** [comment] 2017-09-04 14:39
+1 InfluxDB and Grafana Images not found. 
Error : 
```
docker pull gcr.io/google_containers/heapster-grafana-amd64:v4.4.3
Error response from daemon: manifest for gcr.io/google_containers/heapster-grafana-amd64:v4.4.3 not found

```

**Comment by voyalab** [comment] 2017-09-04 14:41
@luxas Both images are not in gcr: **InfluxDB** and **Grafana**. Although the issue is created for InfluxDB. Please check Grafana too.

**Comment by luxas** [comment] 2017-09-05 19:20
This is now fixed as @piosz pushed the images, ref https://github.com/kubernetes/heapster/issues/1783

**Comment by voyalab** [comment] 2017-09-06 10:01
Thanks, @luxas

**Closed** 2017-09-07 15:21 UTC
