### ISSUE TITLE
influxdb sink not work with option retention

### ISSUE THREAD

**Issue by lidajia** [kubernetes/heapster#1843] opened 2017-10-12 08:45 UTC
--sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086?retention=1h0m0s
the option retention dose not work.
using curl get the default retention policy of dababase k8s, the retention is set to 0s

env:
heapster 1.4.0
influxdb v1.1.1

in the function createDatabase, when command 'CREATE DATABASE %s WITH NAME "default"`, sink.c.DbName' execute, the default retention policy was created, and retention is set to 0s, and the funciton createRetentionPolicy will not be execute.

```
func (sink *influxdbSink) createDatabase() error {
	if err := sink.ensureClient(); err != nil {
		return err
	}

	if sink.dbExists {
		return nil
	}
	q := influxdb.Query{
		Command: fmt.Sprintf(`CREATE DATABASE %s WITH NAME "default"`, sink.c.DbName),
	}

	if resp, err := sink.client.Query(q); err != nil {
		if !(resp != nil && resp.Err != nil && strings.Contains(resp.Err.Error(), "already exists")) {
			err := sink.createRetentionPolicy()
			if err != nil {
				return err
			}
		}
	}

	sink.dbExists = true
	glog.Infof("Created database %q on influxDB server at %q", sink.c.DbName, sink.c.Host)
	return nil
}
```

**Comment by BlueMonday** [comment] 2017-10-21 00:03
This is a duplicate of: https://github.com/kubernetes/heapster/issues/1579

**Comment by DirectXMan12** [comment] 2017-10-25 18:37
closed as duplicate

**Closed by DirectXMan12** 2017-10-25 18:37 UTC
Labels: bug, sink/influxdb
