### ISSUE TITLE
Heapster should be able to write custom metrics from a kube cluster running outside GCP

### ISSUE THREAD

**Issue by activars** [kubernetes/heapster#1201] opened 2016-06-23 09:46 UTC
The current `gcm` sink only works with GCP metadata endpoint.

When running heapster in kube cluster, it would be nice that heapster can:
1. Detect if the environment is outside GCP
2. If a credential is provided for Stackdriver/GCM, it can write metrics to GCM after authenticated with GCP private key authentication

note: created an issue referring to the feature request in #1175

**Comment by markine** [comment] 2017-08-24 15:23
This would be super nice. I've been able to get the Stackdriver monitoring agent running in Kubernetes 1.7.2 on AWS with a service account json private key mounted in /etc/google/auth/. It would be great if we could follow a similar pattern with heapster.

**Comment by markine** [comment] 2017-08-24 15:36
FYI looks like https://github.com/kubernetes/heapster/pull/1657 got merged.

**Comment by markine** [comment] 2017-08-24 16:02
I've confirmed that the above patch works by building master privately.

**Closed** 2017-09-07 18:02 UTC
