### ISSUE TITLE
handlers.go No metrics for pod

### ISSUE THREAD

**Issue by r0bj** [kubernetes/heapster#1470] opened 2017-01-19 13:57 UTC
heapster: 1.3.0-beta.0
kubernetes: 1.5.2
docker: 1.12.6
OS: ubuntu 14.04

I'm trying to use horizontal autoscaling feature for my logstash processing containers.
Deployment definition:
https://gist.github.com/r0bj/c787265c932ba8a1de1467cebd2a906d

So I run:
kubectl autoscale deployment logstash --cpu-percent=50 --min=10 --max=30

kube-controller-manager logs:
```
W0119 13:54:06.641342       1 horizontal.go:104] Failed to reconcile logstash: failed to compute desired number of replicas based on CPU utilization for Deployment/ops/logstash: failed to get CPU utilization: unable to get metrics for resource cpu: no metrics returned from heapster
```

heapster logs:
```
I0119 13:48:36.675011       1 handlers.go:265] No metrics for container logstash in pod ops/logstash-3396208917-6lzxt
I0119 13:48:36.675017       1 handlers.go:216] No metrics for pod ops/logstash-3396208917-6lzxt
I0119 13:48:36.675025       1 handlers.go:265] No metrics for container logstash in pod ops/logstash-3396208917-3j8sj
I0119 13:48:36.675029       1 handlers.go:216] No metrics for pod ops/logstash-3396208917-3j8sj
I0119 13:48:36.675037       1 handlers.go:265] No metrics for container logstash in pod ops/logstash-3396208917-92f96
I0119 13:48:36.675041       1 handlers.go:216] No metrics for pod ops/logstash-3396208917-92f96
I0119 13:49:06.636598       1 handlers.go:216] No metrics for pod ops/logstash-3396208917-jll9j
I0119 13:49:06.636606       1 handlers.go:216] No metrics for pod ops/logstash-3396208917-3j8sj
I0119 13:49:06.636613       1 handlers.go:216] No metrics for pod ops/logstash-3396208917-7zt2j
```

**Comment by Dmitry1987** [comment] 2017-02-06 15:21
Hi @r0bj ,
did you find a solution?  I'm stuck with same.. heapster same version, but on k8s 1.5.1

**Comment by r0bj** [comment] 2017-02-06 15:26
@Dmitry1987 unfortunately no, I didn't find any solution for that.

**Comment by DirectXMan12** [comment] 2017-02-06 16:59
What log level was Heapster running at?  Can you run at a higher one?  Did you see any messages about skipping rate calculations in your logs?  How about other errors?

**Comment by DirectXMan12** [comment] 2017-02-06 16:59
Do you have thin_ls enabled?

**Comment by Dmitry1987** [comment] 2017-02-06 17:45
I think it's because Rancher didn't installed cAdvisor on nodes... some post says they use "docker stats" directly for the dashboard, and 'removed cAdvisor' from installation since Rancher version 1.1 or something like that ...  will try tomorrow to setup cAdvisor sidecar on all nodes and see if it helps.

**Comment by DirectXMan12** [comment] 2017-02-06 18:57
yeah, I'm not sure how rancher works, but basically, Heapster gets its metrics via the Kubelet stats summary API.  Kubelet derives these stats via a built-in copy of cAdvisor, so I'm not sure how much good a sidecar cAdvisor will do.  Does Rancher just not support the HPA at all?

**Comment by Dmitry1987** [comment] 2017-02-07 09:13
@DirectXMan12  seems like they don't, because my current setup is the "out of the box" latest Rancher 1.3 with latest Kubernetes from it's catalog (Rancher creates K8s infra containers from a template), and Heapster+grafana+influxDB  stack from catalog doesn't show/collect any pod stats. Grafana shows "node" stats though. so i'm trying to understand now how to make heapster receive it's needed data.
Heapster log shows this non stop:  
```
listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces.
handlers.go:216] No metrics for pod xxxxxxxxxxx
handlers.go:265] No metrics for container   xxxxxxxxxx
handlers.go:216] No metrics for pod xxxxxxxxxxx
handlers.go:265] No metrics for container   xxxxxxxxxx
```

and funny thing is, the pods it says "no metric from" are the 2 pods I applied HPA on their deployment. it doesn't seem to even try to fetch info about other pods, which is weird. Will be reading about how all this works...  

using  "kubernetes/heapster:canary" version.

will be glad for any advice or idea about what it might be  :)

**Comment by r0bj** [comment] 2017-02-09 12:59
@DirectXMan12 yes I can see some skipping rate calculations in logs with `--vmodule=*=4`:
```
I0209 12:54:35.152486       1 rate_calculator.go:51] Skipping rates for namespace:ops/pod:logstash-1576143268-3xjwl/container:logstash - different create time new:2017-02-08 18:58:30.485800088 +0000 UTC  old:0001-01-01 00:00:00 +0000 UTC
```

More logs with `--vmodule=*=4`:
https://gist.github.com/r0bj/5b89014cd7dd3f37cb70fa89f1ab6e8a

**Comment by r0bj** [comment] 2017-02-09 13:04
I'm not using Rancher, just bare metal kubernetes installation.

**Comment by DirectXMan12** [comment] 2017-02-13 20:34
> and funny thing is, the pods it says "no metric from" are the 2 pods I applied HPA on their deployment. it doesn't seem to even try to fetch info about other pods, which is weird. Will be reading about how all this works...

Yeah, that message is actually logged from the API handlers when they can't find the info in the in-memory cache.

> . so i'm trying to understand now how to make heapster receive it's needed data.
Heapster log shows this non stop:

If the Kubelet doesn't serve the summary API, there's not much we can do.  If the Kubelet does serve the summary API, then we have something to work with.  Is the Rancher Kubelet serving the summary API?

**Comment by DirectXMan12** [comment] 2017-02-13 20:36
@r0bj 

`W0209 12:54:37.625232 1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces`

If I had to guess, there's a version mismatch in your cluster, or something else is up -- the "skipping rate calculation" message you posted is generally caused by stub pod entries.

**Comment by Dmitry1987** [comment] 2017-02-14 08:21
For me this was solved with Rancher 1.4.0  which brings new "stack" of K8s with it... after I updated the K8s components, suddenly Kubelets started collecting data and heapster filled influxDB with all metrics, now I have everything in Grafana :+1:  as expected.  Seems like Rancher devs put back the cAdvisor (in previous release it was without it, I've read on their forum). 

but still sometimes I see the  "can not retrieve list of objects using index : object has no ....."  errors logged, have no idea what causes this...   btw, what are "stub pods" @DirectXMan12  ?  I'm doing manual cleanup of any exited containers on hosts, and manual cleanup of unused images, can this cause such issue?

**Comment by DirectXMan12** [comment] 2017-02-14 15:50
>  btw, what are "stub pods" @DirectXMan12 ?

Stub pods are fake pod entries created when Heapster has some data from one source, but not from another.  They cause all sorts of issues, but you usually don't see them with the summary API

>  I'm doing manual cleanup of any exited containers on hosts, and manual cleanup of unused images, can this cause such issue?

That *maybe* could cause issues... not sure.  Is the built-in Kube cleanup not working sufficiently?  Kube should do that stuff automatically as necessary.

**Comment by Dmitry1987** [comment] 2017-02-14 20:55
oh, i totally forgot I've read somewhere about kubelet cleaning the host (but only when gets full, to thresholds, right?).... i need to remove my manual cleaner cron job for sure. thanks :)

**Comment by r0bj** [comment] 2017-02-14 21:00
@DirectXMan12 In my case I don't do any manual cleanup. All k8s components are in version 1.5.2, docker is 1.12.6.

**Comment by aeoluswing** [comment] 2017-02-20 11:16
indeed,@Dmitry1987,i have been stuck this issue before and discover the 'broken metrics' matter about rancher-k8s(version1.1 or higher).The reason is just for the state collection method which via docker stat and container stat,but for heapster the more appropriate choice is cAdvisor(summary api for more efficient approach).after upgrade the rancher version deployed recently(v1.4 or v1.4.1),you can find the "lost pod* and container* metrics" in your back-end storage(e.g. influxdb) which will get the same response when invoke the API.
what is worth mentioning,if i just upgrade the k8s components,"no metrics" errors arised.But cleaning the etcd cluster will vanish this.So i make a guess at the metrics mechanism,etcd maybe not renovate if you just update component.
good luck ^_^

**Comment by Dmitry1987** [comment] 2017-02-20 11:39
Thanks @aeoluswing ,
as I mentioned, in rancher 1.4 the data is being collected properly, and Heapster+Grafan+InfluxDB stack from catalog works well. Regarding those logs:
```
can not retrieve list of objects using index : object has no .....
```
I always see them.  Do you mean a redeploy/cleanup of etcd helps get rid of those?  cleanup sounds a bit frightening, as all K8s data stored in there :D  , what did you do when cleaning up etcd?

**Comment by aeoluswing** [comment] 2017-02-20 12:48
@Dmitry1987,etcd records the registry kv info for k8s,my step just trigger this procedure,i suggest a data validation for cadvisor collecting metrics configurations,as we all known,cadvisor can collect any structured information(including name of metrics and regexps).Make sure cAdvisor application-metric labels(prefix is io.cadvisor.metric) contain the pod and container fields(i think these might be more easier than cleanup for prod)

**Comment by Dmitry1987** [comment] 2017-02-20 13:42
Interesting... though I have no idea where cAdvisor hiding in those modified Rancher K8s images (they recompile some of the components, and put them all into custom special docker images), but it's worth to research. Thanks for the info @aeoluswing  :+1:

**Comment by aeoluswing** [comment] 2017-02-20 13:53
My pleasure.Capturing different structured metrics is a very helpful for cluster research,especially on cluster performance and schedule.It's a  a piece of cake for discussion on any topic about k8s,docker and rancher.haha^_^

**Comment by mlmhl** [comment] 2017-02-23 01:33
Thanks @DirectXMan12 

> I0209 12:54:35.152486       1 rate_calculator.go:51] Skipping rates for namespace:ops/pod:logstash-1576143268-3xjwl/container:logstash - different create time new:2017-02-08 18:58:30.485800088 +0000 UTC  old:0001-01-01 00:00:00 +0000 UTC

As you mentioned, the "skipping rate" message is caused by a version mismatch in the cluster, do you know witch version is mismated, the heapster vs. k8s or k8s vs. etcd? 

And in this message the old create time is "0001-01-01 00:00:00 +0000 UTC", looks like not set. 
According to my understanding, the metric data is retrieved from cadvisor, witch is embed in kubelet, are there any wrong with kubelet?

**Comment by DirectXMan12** [comment] 2017-02-23 20:45
> As you mentioned, the "skipping rate" message is caused by a version mismatch in the cluster, do you know witch version is mismated, the heapster vs. k8s or k8s vs. etcd?

I was referring to heapster vs k8s.

> And in this message the old create time is "0001-01-01 00:00:00 +0000 UTC", looks like not set.
According to my understanding, the metric data is retrieved from cadvisor, witch is embed in kubelet, are there any wrong with kubelet?

That happens usually when heapster has to create a placeholder entry because it doesn't have some data when it needs it.

**Comment by jeremywu0127** [comment] 2017-05-26 06:35
I have met this issue with k8s version `1.6.3`, the `kubectl get hpa` shows like
```
#kubectl get hpa
NAME         REFERENCE               TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
php-apache   Deployment/php-apache   <UNKNOWN> / 50%   1         10        1          19h
```
the logs of heapster shows like
```
I0526 05:52:59.974002       1 handlers.go:264] No metrics for container php-apache in pod default/php-apache-3933604115-ssq2r
I0526 05:52:59.974789       1 handlers.go:215] No metrics for pod default/php-apache-3933604115-ssq2r
I0526 05:53:29.980479       1 handlers.go:215] No metrics for pod default/php-apache-3933604115-ssq2r
I0526 05:53:59.987180       1 handlers.go:215] No metrics for pod default/php-apache-3933604115-ssq2r
```
the php-apache  is
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: gcr.io/google_containers/hpa-example
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
```
the hpa logs like 
```

I0526 14:17:28.287910   28262 horizontal.go:515] Successfully updated status for php-apache
E0526 14:17:28.288323   28262 horizontal.go:201] failed to compute desired number of replicas based on listed metrics for Deployment/default/php-apache: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
I0526 14:17:58.282302   28262 horizontal.go:515] Successfully updated status for php-apache
E0526 14:17:58.282334   28262 horizontal.go:201] failed to compute desired number of replicas based on listed metrics for Deployment/default/php-apache: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
```
then I add resource quta in php-apache by referring [#6293](https://github.com/openshift/origin/issues/6293), it works fine.
new php-apache looks like:
```
#cat php-apche.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: gcr.io/google_containers/hpa-example
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
```
I guess since k8s version `1.6`,  `hpa` support custom metrics more than cpu and memory,  k8s may not set default metric, so we must manually write resource quta in deployment

**Comment by Dmitry1987** [comment] 2017-05-27 16:38
@jeremywu0127 ,  you should verify your Heapster instance can reach all nodes on needed ports and that other components can reach it back (500 and 9000 something, please check in heapster docs...)  verify the kubelet ports are open to access for Heapster. I had a very similar scenario, reason was Heapster not reaching all servers (as a test - open all traffic between server where Heapster hosted and few other nodes with pods, to see if you'll suddenly have HPA working for those pods). 
hope it helps.

**Comment by jeremywu0127** [comment] 2017-06-02 17:41
@Dmitry1987 sorry for late response. `heapster` and other `components` (kubelet and kube-proxy) run on same node, I manually run `curl`, it looks like
```
#curl http://172.16.97.3:8082/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=run%3Dphp-apache
{
  "metadata": {},
  "items": null
 }
```
seems heapster can reach each other component, any ideas about the problem?

**Comment by Dmitry1987** [comment] 2017-06-02 18:25
mm.. no idea what else might cause this, especially on same host o_O really strange.. please share if you solve it :)

**Comment by Dmitry1987** [comment] 2017-06-02 18:28
@jeremywu0127  can you try switching to different versions of heapster? maybe something with the schema changes... btw regarding RBAC, what if the policies are not configured properly and block 'something somewhere'?  (I'm getting lost in the rising complexity of k8s with each new version, still can't get my head around all aspects related to RBAC.. but worth to check this direction in troubleshooting... just a guess)

**Comment by beinnova** [comment] 2017-06-08 12:47
Hi, I have the same problem on GKE cluster. After updating to 1.6.2 version I can't see metrics.

**Comment by jeremywu0127** [comment] 2017-06-09 06:54
@Dmitry1987 I add resources request it works. manifests like the following
before:
```
      containers:
        - name: netacuity
          image: myhub.com/netacuity:latest
          imagePullPolicy: Always
```
now:
```
      containers:
        - name: netacuity
          image: myhub.com/netacuity:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
```
seems that it must specify the request resources of a container, then `hpa` and `heapster`  work

**Comment by DirectXMan12** [comment] 2017-06-09 15:08
HPA specifically needs requests.  This is documented in the HPA documentation.  Simply accessing the metrics from Heapster should not require requests to be set.

**Comment by Dmitry1987** [comment] 2017-06-09 16:33
Hey guys, thanks for reporting back, it's a useful info :+1:

**Comment by r0bj** [comment] 2017-06-27 15:12
heapster: 1.4.0-beta.0
kubernetes: 1.6.4
docker: 1.12.6
OS: ubuntu 14.04

```
I0627 14:14:55.203314       1 rate_calculator.go:53] Skipping rates for namespace:ops/pod:logstash-1163116248-c1gnc - different create time new:2017-06-07 09:13:42.843665465 +0000 UTC  old:0001-01-01 00:00:00 +0000 UTC
I0627 14:14:55.203350       1 rate_calculator.go:53] Skipping rates for namespace:prod/pod:helios-486069052-cpdfq/container:helios - different create time new:2017-06-20 13:40:54.279525385 +0000 UTC  old:0001-01-01 00:00:00 +0000 UTC
I0627 14:14:55.203367       1 rate_calculator.go:53] Skipping rates for namespace:logs-ingress/pod:fluentd-listener-3760655665-x7b0k/container:fluentd-listener - different create time new:2017-05-18 09:49:33.437557364 +0000 UTC  old:0001-01-01 00:00:00 +0000 UTC
I0627 14:14:55.203462       1 pod_based_enricher.go:129] Container namespace:ops/pod:celery-mediawiki-main-4064416888-zkwqz/container:mediawiki-main not found, creating a stub
I0627 14:14:55.203545       1 pod_based_enricher.go:100] Pod namespace:kube-system/pod:calico-node-xv682 not found, creating a stub
I0627 14:14:55.203579       1 pod_based_enricher.go:129] Container namespace:kube-system/pod:calico-node-xv682/container:install-cni not found, creating a stub
[...]
I0627 14:14:55.213923       1 node_aggregator.go:44] No metric for node node:k8s-worker-s11, cannot perform node level aggregation.
I0627 14:14:55.213941       1 node_aggregator.go:44] No metric for node node:k8s-controller-s3, cannot perform node level aggregation.
I0627 14:14:55.213953       1 node_aggregator.go:44] No metric for node node:k8s-worker-s12, cannot perform node level aggregation.
```

More logs:
https://gist.github.com/r0bj/29cb420a761f0dd71d29887e4994d200

Horizontal pod autoscaling fails with this issue.

Is there anything I can do to debug it deeper?

**Comment by DirectXMan12** [comment] 2017-06-27 15:21
@r0bj which source are you using? `--sink=kubernetes` or `--sink=kubernetes.summary_api`?

**Comment by DirectXMan12** [comment] 2017-06-27 15:26
Ok, so first try with `--source=kubernetes.summary_api:https://kubernetes.default.svc`.  If that doesn't work, check if you can you manually curl the summary API endpoint from the Heapster pod.  The summary API endpoint is at `https://$NODE:10255/stats/summary`.

**Comment by r0bj** [comment] 2017-06-29 09:25
@DirectXMan12 thanks for the hint, so now messages are little different:
```
I0629 09:06:25.582615       1 rate_calculator.go:49] Skipping rate calculations for namespace:kube-system/pod:kube-proxy-247jk - new batch (2017-06-29 09:06:14 +0000 UTC) was not scraped strictly after old batch (2017-06-29 09:06:14 +0000 UTC)
[...]
I0629 09:06:29.689475       1 handlers.go:215] No metrics for pod fandom/upstream-prod-1277166791-ghcjp
```

Full log:
https://gist.github.com/r0bj/07e4854728862e5cf1ef1c13b9102aa7

So instead of: `different create time new:[...]  old:0001-01-01 00:00:00 +0000 UTC` there is now: `new batch ([...]) was not scraped strictly after old batch ([...])`

kubelet summary API endpoint seems working fine:
```
# docker ps -qf "label=io.kubernetes.container.name=heapster" | xargs docker inspect --format '{{.State.Pid}}'
14691
# nsenter -t 14691 -n curl http://k8s-worker-s10:10255/stats/summary
{
  "node": {
   "nodeName": "k8s-worker-s10",
   "systemContainers": [
    {
     "name": "kubelet",
     "startTime": "2017-06-27T22:12:25Z",
     "cpu": {
      "time": "2017-06-29T09:22:24Z",
      "usageNanoCores": 3744712489,
      "usageCoreNanoSeconds": 13508107484362565
     },
     "memory": {
      "time": "2017-06-29T09:22:24Z",
      "availableBytes": 88867352576,
      "usageBytes": 41442099200,
      "workingSetBytes": 12505178112,
      "rssBytes": 502865920,
      "pageFaults": 14161385628,
      "majorPageFaults": 37805
     },
     "userDefinedMetrics": null
    },
[...]
```

Full stats summary:
https://gist.github.com/r0bj/72049ac2ca2d2e02f62b2c44127b0143

Stats for other nodes are also available from heapster pod.

**Comment by DirectXMan12** [comment] 2017-06-29 15:16
so, I'm guessing you're hitting a bug where your Heapster collection interval is not always larger than the cAdvisor collection interval.  What's your Heapster collection interval?  Default?  We had a bug a while back where thin_ls stats were causing issues, but that should have gotten merged a while ago...

**Comment by DirectXMan12** [comment] 2017-06-29 15:19
hmm... you're using 1.5.2... that doesn't have the patch for disabling thin_ls stats...
try bind-mounting /dev/null over the thin_ls binary and see if that fixes your issue.

**Comment by r0bj** [comment] 2017-06-29 15:48
I've used hepaster with `--metric-resolution=10s`. Now I've switched to `--metric-resolution=20s` and it seems that there is no issue.

I've done some digging and it seems that heapster polling interval should be > 2*
polling duration of cadvisor:
https://github.com/kubernetes/kubernetes/issues/18044#issuecomment-161435365

And cadvisor polling interval is currently hardcoded to 10s:
https://github.com/kubernetes/kubernetes/pull/19374

So the minimal heapster polling interval can be 20s.
@DirectXMan12 Does it make any sense to you?

**Comment by DirectXMan12** [comment] 2017-06-29 17:18
I *really* need to put this in a document somewhere:
With a set collection interval of 10s in cAdvisor, the *actual* cAdvisor collection interval can be up to 30s, due to jitter and backoff mechanisms.  Your Heapster collection interval should be no lower than 30s.

**Comment by piosz** [comment] 2017-07-04 06:51
@r0bj out of curiosity why do you need lower `metric-resolution`?

**Comment by r0bj** [comment] 2017-07-04 08:54
@piosz I can live with 30s interval of heapster polling, I just use 10s resolution in my metrics infrastructure so it was natural idea.
Anyway, thanks for help!

**Comment by DirectXMan12** [comment] 2017-07-05 17:28
closing since the issue seems to be resolved.

**Closed by DirectXMan12** 2017-07-05 17:28 UTC
Labels: support

**Comment by zjzhangkui** [comment] 2017-08-23 07:26
@r0bj Does adding --housekeeping-interval=5s flag in kubelet work? I tried set this flag and metric-resolution set 15s, but still got no metrics returned from heapster error.  If changed metric-resolution to 20s, the issue is gone. Seams the flag housekeeping-interval set in kubelet not work. I restart the kubelet and had seen the flag with systemctl status kubelet.
