### ISSUE TITLE
kubeadm cluster can't run grafana from default influxdb deploy

### ISSUE THREAD

**Issue by gpjt** [kubernetes/heapster#1702] opened 2017-06-26 17:44 UTC
It looks like the grafana.ini file isn't being put into the pod.

Some diagnostics, let me know if anything else would be useful:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl create -f deploy/kube-config/influxdb/
deployment "monitoring-grafana" created
service "monitoring-grafana" created
serviceaccount "heapster" created
deployment "heapster" created
service "heapster" created
deployment "monitoring-influxdb" created
service "monitoring-influxdb" created
$ kubectl get pod --all-namespaces
NAMESPACE     NAME                                               READY     STATUS             RESTARTS   AGE
default       admin-4-pod                                        1/1       Running            2          1h
kube-system   etcd-giles-devalwaysonmaster1                      1/1       Running            1          5h
kube-system   heapster-1428305041-rsgkz                          1/1       Running            0          5s
kube-system   kube-apiserver-giles-devalwaysonmaster1            1/1       Running            1          5h
kube-system   kube-controller-manager-giles-devalwaysonmaster1   1/1       Running            1          5h
kube-system   kube-dns-692378583-1pvdt                           3/3       Running            3          5h
kube-system   kube-proxy-fvcd1                                   1/1       Running            2          5h
kube-system   kube-proxy-p3sv5                                   1/1       Running            1          5h
kube-system   kube-scheduler-giles-devalwaysonmaster1            1/1       Running            1          5h
kube-system   monitoring-grafana-2108077385-d4xv4                0/1       CrashLoopBackOff   1          5s
kube-system   monitoring-influxdb-3480804314-4xh9g               1/1       Running            0          5s
kube-system   weave-net-8619b                                    2/2       Running            2          5h
kube-system   weave-net-zvt0l                                    2/2       Running            2          5h
$ kubectl logs --namespace kube-system monitoring-grafana-2108077385-d4xv4 
Starting a utility program that will configure Grafana
Starting Grafana in foreground mode
t=2017-06-26T17:39:28+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory%!(EXTRA []interface {}=[])"
$ git show
commit b7884daeab3ef075119d549f9411c3826e568a75
Merge: a729275 c9bc904
Author: Solly Ross <directxman12+github@gmail.com>
Date:   Fri Jun 23 14:40:54 2017 -0400
    Merge pull request #1607 from AlmogBaku/es5-support
    
    ElasticSearch 5 support
```

**Comment by wangwu50** [comment] 2017-06-27 01:57
I have the same question

**Comment by evhfla** [comment] 2017-06-27 04:42
Same problem here

**Comment by narunask** [comment] 2017-06-27 14:46
I second that, same problem.

**Comment by DirectXMan12** [comment] 2017-06-27 15:27
@piosz did something go wrong with the latest release of the Grafana pod?

**Comment by yukiman76** [comment] 2017-06-27 16:06
Same problem here

**Comment by yukiman76** [comment] 2017-06-27 16:19
![screen shot 2017-06-27 at 12 18 39 pm](https://user-images.githubusercontent.com/8270088/27598206-d03536fc-5b32-11e7-9e2f-52e62bd11d2c.png)
looks like the  grafana.ini  is not in the image

**Comment by yukiman76** [comment] 2017-06-27 17:10
basic error 
/ # /usr/bin/setup_grafana
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp 127.0.0.1:3000: getsockopt: connection refused. Retrying after 5 seconds...

**Comment by mjsilva** [comment] 2017-06-28 05:17
Any solution while this is not fixed, use a previous version?

**Comment by mjsilva** [comment] 2017-06-28 05:24
Confirm that if you use `gcr.io/google_containers/heapster-grafana-amd64:v4.0.2` it works

**Comment by narunask** [comment] 2017-06-28 09:42
Unfortunately for me the older version doesn't work either...

```
$ kubectl -n kube-system logs monitoring-grafana-2107815241-zd7p5
Starting a utility program that will configure Grafana
Starting Grafana in foreground mode
t=2017-06-28T09:36:01+0000 lvl=info msg="Starting Grafana" logger=main version=v4.0.2 commit=unknown-dev compiled=2017-06-28T09:36:01+0000
t=2017-06-28T09:36:01+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-06-28T09:36:01+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-06-28T09:36:01+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-06-28T09:36:01+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-06-28T09:36:01+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SERVER_PROTOCOL=http"
t=2017-06-28T09:36:01+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=/"
t=2017-06-28T09:36:01+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ENABLED=true"
t=2017-06-28T09:36:01+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
t=2017-06-28T09:36:01+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_BASIC_ENABLED=false"
t=2017-06-28T09:36:01+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-06-28T09:36:01+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-06-28T09:36:01+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-06-28T09:36:01+0000 lvl=info msg="Path Plugins" logger=settings path=/usr/share/grafana/data/plugins
t=2017-06-28T09:36:01+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-06-28T09:36:01+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-06-28T09:36:01+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
t=2017-06-28T09:36:02+0000 lvl=info msg="Executing migration" logger=migrator id="create user table"
t=2017-06-28T09:36:02+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.login"
t=2017-06-28T09:36:04+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.email"
t=2017-06-28T09:36:05+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_login - v1"
t=2017-06-28T09:36:05+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_email - v1"
t=2017-06-28T09:36:05+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table user to user_v1 - v1"
t=2017-06-28T09:36:05+0000 lvl=info msg="Executing migration" logger=migrator id="create user table v2"
t=2017-06-28T09:36:05+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_login - v2"
t=2017-06-28T09:36:05+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_email - v2"
t=2017-06-28T09:36:05+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table user_v1"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create temp user table v1-7"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_email - v1-7"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_org_id - v1-7"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_code - v1-7"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_status - v1-7"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create star table"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index star.user_id_dashboard_id"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create org table v1"
t=2017-06-28T09:36:06+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_name - v1"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="create org_user table v1"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_org_user_org_id - v1"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_user_org_id_user_id - v1"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-06-28T09:36:07+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-06-28T09:36:07+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account_user"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard table"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="add index dashboard.account_id"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_account_id_slug"
t=2017-06-28T09:36:07+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_tag table"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_tag.dasboard_id_term"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_dashboard_tag_dashboard_id_term - v1"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table dashboard to dashboard_v1 - v1"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard v2"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_dashboard_org_id - v2"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_org_id_slug - v2"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="copy dashboard v1 to v2"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="drop table dashboard_v1"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard.data to mediumtext v1"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="Add column updated_by in dashboard - v2"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="Add column created_by in dashboard - v2"
t=2017-06-28T09:36:08+0000 lvl=info msg="Executing migration" logger=migrator id="Add column gnetId in dashboard"
t=2017-06-28T09:36:09+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for gnetId in dashboard"
t=2017-06-28T09:36:09+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_id in dashboard"
t=2017-06-28T09:36:09+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for plugin_id in dashboard"
t=2017-06-28T09:36:09+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for dashboard_id in dashboard_tag"
t=2017-06-28T09:36:09+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table"
t=2017-06-28T09:36:09+0000 lvl=info msg="Executing migration" logger=migrator id="add index data_source.account_id"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index data_source.account_id_name"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_data_source_account_id - v1"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_data_source_account_id_name - v1"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table data_source to data_source_v1 - v1"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table v2"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_data_source_org_id - v2"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_data_source_org_id_name - v2"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table data_source_v1 #2"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="Add column with_credentials"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="Add secure json data column"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="create api_key table"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id"
t=2017-06-28T09:36:10+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.key"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id_name"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_api_key_account_id - v1"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_api_key_key - v1"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_api_key_account_id_name - v1"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table api_key to api_key_v1 - v1"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="create api_key table v2"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_api_key_org_id - v2"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_api_key_key - v2"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_api_key_org_id_name - v2"
t=2017-06-28T09:36:11+0000 lvl=info msg="Executing migration" logger=migrator id="copy api_key v1 to v2"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table api_key_v1"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_snapshot table v4"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="drop table dashboard_snapshot_v4 #1"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_snapshot table v5 #2"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_snapshot_key - v5"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_snapshot_delete_key - v5"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_dashboard_snapshot_user_id - v5"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard_snapshot to mediumtext v2"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create quota table v1"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_quota_org_id_user_id_target - v1"
t=2017-06-28T09:36:12+0000 lvl=info msg="Executing migration" logger=migrator id="create plugin_setting table"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_plugin_setting_org_id_plugin_id - v1"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_version to plugin_settings"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="create session table"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table playlist table"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table playlist_item table"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="create playlist table v2"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="create playlist item table v2"
t=2017-06-28T09:36:13+0000 lvl=info msg="Executing migration" logger=migrator id="drop preferences table v2"
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="drop preferences table v3"
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="create preferences table v3"
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="create alert table v1"
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert org_id & id "
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert state"
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert dashboard_id"
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="create alert_notification table v1"
t=2017-06-28T09:36:14+0000 lvl=info msg="Executing migration" logger=migrator id="Add column is_default"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert_notification org_id & name"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old annotation table v4"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="create annotation table v5"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 0 v3"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 1 v3"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 2 v3"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 3 v3"
t=2017-06-28T09:36:15+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 4 v3"
t=2017-06-28T09:36:16+0000 lvl=info msg="Created default admin user: [admin]"
t=2017-06-28T09:36:16+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-06-28T09:36:16+0000 lvl=warn msg="Plugin dir does not exist" logger=plugins dir=/usr/share/grafana/data/plugins
t=2017-06-28T09:36:16+0000 lvl=info msg="Plugin dir created" logger=plugins dir=/usr/share/grafana/data/plugins
t=2017-06-28T09:36:16+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-06-28T09:36:16+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-06-28T09:36:16+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
```

```
$ kubectl -n kube-system exec monitoring-grafana-2107815241-zd7p5 -- netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::3000                 :::*                    LISTEN      1/grafana-server
```

**Comment by yuananf** [comment] 2017-06-29 09:43
Same problem here

**Comment by AlterEgo7** [comment] 2017-06-29 13:28
Latest release has 4.2.0 grafana image version. Changing it to 4.0.2 fixes the issue. Not sure if this is a typo in the container image version or not.

**Comment by narunask** [comment] 2017-06-29 14:41
That's not a typo, new version has been added with the #05f739ef6e7fddb265b9b73b2c65b58ef5e1b500

**Comment by christiaan-janssen** [comment] 2017-06-30 08:30
I'm trying with `gcr.io/google_containers/heapster-grafana-amd64:v4.0.2` but then I get:

```Back-off restarting failed container
Error syncing pod, skipping: failed to "StartContainer" for "grafana" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=grafana pod=monitoring-grafana-2108077385-736m7_kube-system(e382bc28-5cb4-11e7-b2c7-42010a8400a0)"
Failed to pull image "gcr.io/google_containers/heapster-grafana-amd64": rpc error: code = 2 desc = Error: Status 405 trying to pull repository google_containers/heapster-grafana-amd64: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices"```

**Comment by bishenghua** [comment] 2017-06-30 13:40
it doesn't work:
Starting a utility program that will configure Grafana
Starting Grafana in foreground mode
t=2017-06-30T13:39:23+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory%!(EXTRA []interface {}=[])"
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp 127.0.0.1:3000: getsockopt: connection refused. Retrying after 5 seconds...

**Comment by bishenghua** [comment] 2017-06-30 14:57
i have soved it! Becaues it has not this file:/etc/grafana/grafana.ini in gcr.io/google_containers/heapster-grafana-amd64:v4.2.0

1. docker pull gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
2. docker run -d --name test -v /tmp/ttt:/tmp/ttt gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
3. docker exec -it test -- cp -rp /etc/grafana /tmp/ttt && docker rm -f test
4. vim Dockerfile:
FROM      gcr.io/google_containers/heapster-grafana-amd64:v4.2.0
MAINTAINER shenghua bi <net.bsh@gmail.com>
COPY /tmp/ttt/grafana /etc/grafana
5. docker build -t="gcr.io/google_containers/heapster-grafana-amd64:v4.2.1" .
6. yon can use your heapster-grafana-amd64:v4.2.1 instead of heapster-grafana-amd64:v4.2.0

it work fine.
Good luck!

**Comment by 4admin2root** [comment] 2017-07-01 15:15
It works with grafana 4.0.2 , but there are no datapoints.

**Comment by tanmaykm** [comment] 2017-07-01 20:24
Ran into this. As a temporary workaround, I am using image `luxas/heapster-grafana-amd64:v4.3.2` instead of `gcr.io/google_containers/heapster-grafana-amd64:v4.2.0`.
Ref: https://github.com/luxas/kubeadm-workshop/blob/master/demos/monitoring/influx-grafana.yaml.

Haven't had time to try out, but maybe copying `sample.ini` (as `grafana.ini`) and `ldap.toml` from `/usr/share/grafana/conf` to `/etc/grafana` would have the same effect.

**Comment by DirectXMan12** [comment] 2017-07-05 17:46
looks like a duplicate of https://github.com/kubernetes/heapster/issues/1709

**Comment by loburm** [comment] 2017-07-18 08:41
It's a duplicate of #1709 

Should be already resolved by new release.

**Closed by loburm** 2017-07-18 08:41 UTC
Labels: bug, image-or-release, sink/influxdb
