### ISSUE TITLE
don't pull images

### ISSUE THREAD

**Issue by SamolazovRoman** [kubernetes/heapster#2063] opened 2018-07-12 07:05 UTC
```
➜  heapster git:(master) ✗ docker image pull k8s.gcr.io/heapster-amd64:v1.5.3
v1.5.3: Pulling from heapster-amd64
c81d386f75aa: Pull complete
eae62af09b36: Pull complete
Digest: sha256:fc33c690a3a446de5abc24b048b88050810a58b9e4477fa763a43d7df029301a
Status: Downloaded newer image for k8s.gcr.io/heapster-amd64:v1.5.3
➜  heapster git:(master) ✗ docker image pull k8s.gcr.io/heapster-influxdb-amd64:v1.5.2
Error response from daemon: manifest for k8s.gcr.io/heapster-influxdb-amd64:v1.5.2 not found
➜  heapster git:(master) ✗ docker image pull k8s.gcr.io/heapster-grafana-amd64:v5.0.4
Error response from daemon: manifest for k8s.gcr.io/heapster-grafana-amd64:v5.0.4 not found
➜  heapster git:(master) ✗
```

**Comment by x13n** [comment] 2018-07-12 15:47
Looks like a duplicate of https://github.com/kubernetes/heapster/issues/2059

**Closed by x13n** 2018-07-12 15:47 UTC
