### ISSUE TITLE
Heapster REST endpoint is not reachable

### ISSUE THREAD

**Issue by muzzy82** [kubernetes/heapster#970] opened 2016-02-12 12:34 UTC
Hi,

I have a single VM (CentOS 7.1) Kubernetes configuration (version: 1.1.0)
My heapster setup is:
_heapster:v0.20.0-alpha5_
_heapster_influxdb:v0.6_
_heapster_grafana:v2.6.0_

Heapster is running well (i.e. no sign of errors in log with increased verbosity):
```bash
[root@kubernetes-monitoring pods]# kubectl logs heapster-v13-2x3qf heapster
I0212 12:27:21.211376       1 heapster.go:59] /heapster --source=kubernetes:'' --sink=influxdb:http://monitoring-influxdb:8086 --metric_resolution=60s --vmodule=*=4
I0212 12:27:21.211673       1 heapster.go:60] Heapster version 0.20.0-alpha5
I0212 12:27:21.211875       1 configs.go:60] Using Kubernetes client with master "https://10.254.0.1:443" and version "v1"
I0212 12:27:21.211885       1 configs.go:61] Using kubelet port 10255
E0212 12:27:21.225967       1 influxdb.go:185] issues while creating an InfluxDB sink: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: read tcp 10.254.149.83:8086: connection reset by peer, will retry on use
I0212 12:27:21.225987       1 influxdb.go:199] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:k8s
I0212 12:27:21.226001       1 heapster.go:86] Starting with InfluxDB Sink
I0212 12:27:21.226006       1 heapster.go:86] Starting with Metric Sink
I0212 12:27:21.269460       1 heapster.go:155] Starting heapster on port 8082
```
Heapster is listening on its default port, 8082.
However HTTP GET requests return error 404:
```bash
[root@kubernetes-monitoring pods]# kubectl exec -it heapster-v13-2x3qf -c heapster -- /bin/sh
/ # netstat -nalp | grep 8082
tcp        0      0 :::8082                 :::*                    LISTEN      1/heapster
/ # curl http://localhost:8082
404 page not found
```

The same happens when trying to reach it via its service address or through the kube-proxy.
Any ideas?

**Comment by muzzy82** [comment] 2016-02-16 09:44
Further investigating it seems that heapster successfully connects to kubernetes master, kubelet and influxdb:
```bash
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.17.0.3:59005        10.254.0.1:443          ESTABLISHED 1/heapster
tcp        0      0 172.17.0.3:59007        10.254.0.1:443          ESTABLISHED -
tcp        0      0 172.17.0.3:59003        10.254.0.1:443          ESTABLISHED 1/heapster
tcp        0      0 172.17.0.3:53683        10.0.2.15:10255         ESTABLISHED 1/heapster
tcp        0      0 172.17.0.3:38328        10.254.51.113:8086      ESTABLISHED -
tcp        0      0 172.17.0.3:58999        10.254.0.1:443          ESTABLISHED 1/heapster
tcp        0      0 172.17.0.3:38365        10.254.51.113:8086      ESTABLISHED 1/heapster
tcp        0      0 172.17.0.3:59000        10.254.0.1:443          ESTABLISHED 1/heapster
tcp        0      0 172.17.0.3:58996        10.254.0.1:443          ESTABLISHED 1/heapster
tcp        0      0 :::8082                 :::*                    LISTEN      1/heapster
Active UNIX domain sockets (servers and established)
```

However the measurements collected by heapster are somewhat strange:
```bash
InfluxDB shell 0.9.6
> use k8s
Using database k8s
> show measurements
name: measurements
------------------
name
cpu/limit
cpu/node_reservation
cpu/node_utilization
cpu/request
cpu/usage
cpu/usage_rate
filesystem/limit
filesystem/usage
memory/limit
memory/major_page_faults
memory/node_reservation
memory/node_utilization
memory/page_faults
memory/request
memory/usage
memory/working_set
network/rx
network/rx_errors
network/tx
network/tx_errors
uptime
```
According to [storage schema](https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md), measurements should've been postfixed with metric type and unit, e.g.:
uptime_ms_cumulative

**Comment by piosz** [comment] 2016-03-01 14:22
@muzzy82 thanks for reporting this.

`curl http://localhost:8082` is not working by design. Please try `curl http://localhost:8082/api/v1/model/namespaces`.

We decided to change storage schema in influxdb starting from version 0.20 to make it consistent with our REST endpoint and others sinks. It hasn't been documented yet (see #1009). Apologies for that.

I'm closing the issue. Feel free to re-open in case of further problems.

**Closed by piosz** 2016-03-01 14:22 UTC
Labels: Priority/P1
